import { environment } from "src/environments/environment";

export class Parameters {
    Active: any = null;
    AheadBehind: any = null;
    AllStar: any = null;
    ClutchTime: any = null;
    College: any = null;
    ContextFilter: any = null;
    ContextMeasure: any = null;
    Country: any = null;
    DateFrom: any = null;
    DateTo: any = null;
    DraftPick: any = null;
    DraftYear: any = null;
    EndPeriod: any = "10";
    EndRange: any = "28800";
    GameID: any = null;
    GameSegment: any = null;
    Height: any = null;
    Historical: any = "0";
    LastNGames: any = null;
    LeagueID: any = environment.leagueID;
    Location: any = null;
    MeasureType: any = null;
    Month: any = null;
    OpponentTeamID: any = null;
    Outcome: any = null;
    Period: any = null;
    PerMode: any = null;
    PlayerID: any = null;
    PlayerPosition: any = null;
    PointDiff: any = null;
    Position: any = null;
    PORound: any = null;
    RangeType: any = "0";
    RookieYear: any = null;
    Season: any = environment.season;
    SeasonSegment: any = null;
    SeasonType: any = environment.seasonType;
    StartPeriod: any = "0";
    StartRange: any = "0";
    ShotClockRange: any = null;
    TeamID: any = null;
    VsConference: any = null;
    VsDivision: any = null;
    Weight: any = null;
}

